import js from '@eslint/js'
import tseslint from 'typescript-eslint'

export default tseslint.config(
  {
    ignores: [
      '.t/**',
      'artifacts/omarchy-theme/**',
      'artifacts/voice-control-removal/merged-setup/**',
      'artifacts/skill-pill-composer/**',
      'artifacts/omarchy-shell-plugin/**',
      'artifacts/linux-shell-plumbing/**',
      'artifacts/linux-package/**',
      'apps/omarchy/src/**',
      'apps/omarchy/pkg/**',
      'artifacts/e2e-runs/**',
      'artifacts/omarchy-shell-integration/**',
      'artifacts/linux-hyprland-paste/**',
      'artifacts/linux-no-window-controls/**',
      'artifacts/visuals-live/**',
      'artifacts/babysitting-surfaces-run/**',
      'artifacts/remove-personal-chats/**',
      'artifacts/first-run-setup-fit/**',
      'artifacts/disabled-coordinator-voice/**',
      'artifacts/show-thinking/**',
      'artifacts/hidden-player-typing/**',
      'artifacts/computer-use-guidance/**',
      'artifacts/pkg-17-hostconnection/**',
      'artifacts/pkg-34-workspace-git/**',
      'artifacts/main-infra-bundle/**',
      'artifacts/pkg-18-e2e/**',
      'artifacts/windows-askpass/**',

      'artifacts/forge-question-ack/**',
      'artifacts/codex-restored-replies/**',
      'artifacts/workspace-picker/**',
      'artifacts/ios-focus/**',
      'artifacts/iphone-new-threads/**',
      'artifacts/review-*/**',
      'artifacts/renderer-other-bundle-run/**',
      'artifacts/review-644/**',
      'artifacts/review-667/**',
      'artifacts/phase-three-themes/**',
      'artifacts/thread-browser-player/**',
      'artifacts/new-thread-defaults/**',
      'artifacts/codex-questions-thread-agents/**',
      'artifacts/agent-browser/**',
      'artifacts/browser-grant/**',
      'artifacts/remote-thread-tools/**',
      'artifacts/test-iphone/**',
      'artifacts/cloud-iphone/**',
      'artifacts/new-thread-setup/**',
      'artifacts/empty-page-saved-draft/**',
      'artifacts/host-folder-browser-run/**',
      'artifacts/command-receipt/**',
      '.cache/**',
      'artifacts/settled-folder-new-thread/**',
      'artifacts/agents-view/**',
      'artifacts/queued-steering/**',
      'artifacts/screenshot-resize-run/**',
      '.worktrees/**',
      '.claude/tmp/**',
      // Agent worktrees are whole checkouts of this repository, so linting them would lint
      // every file twice and confuse the parser about which tsconfig root it is under.
      '.claude/worktrees/**',
      'coverage/**',
      // Gradle's own output for the Android client: test reports carry generated browser scripts.
      'apps/android/**/build/**',
      'artifacts/question-choices/**',
      'artifacts/sidebar-question/**',
      'artifacts/tools-rail-run/**',
      'artifacts/git-settings/**',
      'artifacts/review-comments-run/**',
      'artifacts/git-interface-run/**',
      'artifacts/worktree-origin-fallback-run/**',
      'artifacts/agent-control-smoke/**',
      'artifacts/activity-performance/**',
      'artifacts/process-creature/**',
      'artifacts/held-action/**',
      'artifacts/working-creature/**',
      'artifacts/background-command/**',
      'artifacts/terminal-loading/**',
      'artifacts/thread-sidebar/**',
      'artifacts/frosted-window/**',
      'artifacts/forge-hand-test/**',
      'artifacts/effort-furnace/**',
      'artifacts/effort-slider/**',
      'artifacts/pending-settings-run/**',
      'artifacts/staged-images-run/**',
      'artifacts/workflow-agent-rows-run/**',
      'artifacts/natural-voice-qa/**',
      'artifacts/tts-bench/**',
      'artifacts/voice-perf/**',
      'artifacts/new-thread-saved-draft/**',
      'artifacts/codex-stream-freeze/**',
      'artifacts/codex-images/**',
      'artifacts/shell-detail-visibility/**',
      'artifacts/issue-146/**',
      'artifacts/codex-connection-recovery/**',
      'artifacts/devin-local-provider/**',
      'node_modules/**',
      'out/**',
      'playwright-report/**',
      'release/**',
      'test-results/**',
    ],
  },
  js.configs.recommended,
  {
    files: ['tests/fixtures/**/*.mjs'],
    languageOptions: { globals: { process: 'readonly', setTimeout: 'readonly', setInterval: 'readonly' } },
  },
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      parserOptions: { tsconfigRootDir: import.meta.dirname },
      globals: {
        __dirname: 'readonly',
        console: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        process: 'readonly',
        window: 'readonly',
      },
    },
  },
  {
    // The LLM bench is a plain Node script.
    files: ['scripts/llm-bench/**/*.mjs'],
    languageOptions: {
      globals: {
        AbortSignal: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
        URL: 'readonly',
      },
    },
  },
  {
    // The ASR bench is a plain Node script.
    files: ['scripts/asr-bench/**/*.mjs'],
    languageOptions: {
      globals: {
        AbortController: 'readonly',
        Blob: 'readonly',
        clearTimeout: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        FormData: 'readonly',
        process: 'readonly',
        setTimeout: 'readonly',
      },
    },
  },
  {
    // The memory bench is a plain Node script.
    files: ['scripts/memeval/**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
      },
    },
  },
  {
    // The perf bench runs in Node but injects callbacks into a Playwright page.
    files: ['scripts/perf-bench/**/*.mjs'],
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        URL: 'readonly',
        window: 'readonly',
      },
    },
  },
)
