import { expect, test } from '@playwright/test'
import { closeSotto, completeFirstRunSetup, launchSottoWithVoice, openPage, openThreads } from './support/sottoLaunch'

test('Crossing keeps dictation, history, settings and sessions usable', async () => {
  const launched = await launchSottoWithVoice()
  const { page } = launched
  page.setDefaultTimeout(5_000)
  try {
    await completeFirstRunSetup(page, { microphone: 'test' })
    // Onboarding hands over to Threads now, so dictation is a deliberate stop.
    await openPage(page, 'Dictate')
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/dictate.png' })
    await page.getByRole('button', { name: 'Start dictation', exact: true }).click()
    await page.getByRole('button', { name: 'Stop', exact: true }).click()
    await page.getByRole('link', { name: 'History', exact: true }).click()
    await expect(page.locator('.history-entry')).toHaveCount(1)
    await page.locator('.history-entry__toggle').click()
    await page.getByRole('button', { name: 'Copy transcript', exact: true }).click()
    await expect(page.getByText('Transcript copied.', { exact: true })).toBeAttached()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/history.png' })
    await page.getByRole('link', { name: 'Settings', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Dictation', exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/settings.png' })
    await page.getByRole('tablist', { name: 'Settings sections' }).getByRole('tab', { name: 'Output', exact: true }).click()
    await page.getByLabel('Paste delay', { exact: true }).fill('10')
    await page.getByLabel('Paste delay', { exact: true }).press('Tab')
    await expect(page.getByText(/between 50 and 1000/i)).toBeVisible()
    await page.getByLabel('Paste delay', { exact: true }).fill('250')
    await page.getByLabel('Paste delay', { exact: true }).press('Tab')
    await expect.poll(() => page.evaluate(async () => (await window.sotto!.getSettings()).pasteDelayMs)).toBe(250)
    await page.getByRole('tablist', { name: 'Settings sections' }).getByRole('tab', { name: 'Agents', exact: true }).click()
    const coordinator = page.locator('#settings-agents')
    await expect(coordinator.getByLabel('Reasoning account', { exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/account.png' })
    await coordinator.getByLabel('Reasoning account', { exact: true }).selectOption('openrouter')
    await coordinator.getByLabel('Reasoning API key', { exact: true }).fill('fixture-only-key')
    await coordinator.getByLabel('Reasoning API key', { exact: true }).press('Tab')
    await expect(coordinator.getByRole('button', { name: 'Remove reasoning API key', exact: true })).toBeVisible()
    await coordinator.getByRole('button', { name: 'Remove reasoning API key', exact: true }).click()
    await expect.poll(() => page.evaluate(async () => (await window.sotto!.agents!.get()).credentials.reasoning)).toBe(false)
    await coordinator.getByLabel('Reasoning account', { exact: true }).selectOption('none')
    await page.getByRole('link', { name: 'Help', exact: true }).click()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/help.png' })
    await page.keyboard.press('Control+k')
    await expect(page.getByRole('searchbox', { name: 'Search transcripts' })).toBeFocused()
    await page.getByRole('tab', { name: 'Agents', exact: true }).click()
    await page.getByRole('button', { name: 'Not now', exact: true }).click()
    // First-run setup's own Coding agents step already connected this computer's provider.
    await expect(page.getByRole('button', { name: 'New session', exact: true })).toBeEnabled()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/agents.png' })
    // The sphere wears the theme; there is no separate orb colour to choose.
    await expect(page.getByRole('button', { name: /orb$/ })).toHaveCount(0)
    const orbColors = await page.locator('canvas.agent-orb').getAttribute('data-orb-colors')
    expect(orbColors).toMatch(/^#[0-9a-f]{6} #[0-9a-f]{6}$/)
    await page.evaluate(async () => { await window.sotto!.updateSettings({ lightTheme: 'citrine', darkTheme: 'citrine' }) })
    await expect(page.locator('html')).toHaveAttribute('data-theme-id', 'citrine')
    await expect(page.locator('canvas.agent-orb')).not.toHaveAttribute('data-orb-colors', orbColors!)
    await page.getByRole('button', { name: 'New session', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'New thread', exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-session.png' })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByRole('button', { name: 'Open Workshop', exact: true }).click()
    await page.getByRole('button', { name: 'Manage this thread', exact: true }).click()
    await page.getByLabel('Prompt', { exact: true }).fill('Keep this draft until I explicitly send it.')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Open Workshop', exact: true }).click()
    await expect(page.getByLabel('Prompt', { exact: true })).toHaveValue('Keep this draft until I explicitly send it.')
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/session.png' })
    await page.getByRole('button', { name: 'Send it', exact: true }).click()
    await expect(page.getByLabel('Session transcript')).toContainText('Keep this draft until I explicitly send it.')
    await page.keyboard.press('Escape')
    await openThreads(page)
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/threads.png' })
    await page.getByRole('button', { name: 'New thread', exact: true }).click()
    const newThread = page.getByRole('dialog', { name: 'New thread', exact: true })
    await expect(newThread).toBeVisible()
    // Choosing the project opens the thread at once, on the defaults from Settings → Agents, with no form after it (#347).
    await newThread.getByRole('button', { name: /^Sotto test / }).click()
    await expect(newThread).toHaveCount(0)
    await expect(page.locator('form.thread-prompt').first()).toBeVisible()
    // The page still names itself for assistive technology; the heading is no longer drawn.
    await expect(page.getByRole('heading', { name: 'Threads', exact: true })).toBeAttached()
  } catch (error) {
    await page.screenshot({ path: 'artifacts/crossing/failure.png' }).catch(() => undefined)
    throw error
  } finally { await closeSotto(launched) }
})
