import { expect, test } from '@playwright/test'
import { launchSotto, closeSotto } from './support/sottoLaunch'

test('Crossing keeps dictation, history, settings and sessions usable', async () => {
  const launched = await launchSotto()
  const { page } = launched
  page.setDefaultTimeout(5_000)
  try {
    await page.getByRole('button', { name: 'Continue' }).click()
    await page.getByRole('button', { name: /test microphone/i }).click()
    await expect(page.getByText(/microphone ready/i)).toBeVisible()
    await page.getByRole('button', { name: 'Continue' }).click()
    await page.getByRole('button', { name: 'Continue' }).click()
    await page.getByRole('button', { name: /finish setup/i }).click()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/dictate.png' })
    await page.getByRole('button', { name: 'Start dictation', exact: true }).click()
    await page.getByRole('button', { name: 'Stop', exact: true }).click()
    await page.getByRole('link', { name: 'History', exact: true }).click()
    await expect(page.locator('.history-entry')).toHaveCount(1)
    await page.locator('.history-entry__toggle').click()
    await page.getByRole('button', { name: 'Copy transcript', exact: true }).click()
    await expect(page.getByText('Transcript copied.', { exact: true })).toBeAttached()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/history.png' })
    await page.getByRole('link', { name: 'Settings', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Dictation', exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/settings.png' })
    await page.getByRole('link', { name: 'Output', exact: true }).click()
    await page.getByLabel('Paste delay', { exact: true }).fill('10')
    await page.getByLabel('Paste delay', { exact: true }).press('Tab')
    await expect(page.getByText(/between 50 and 1000/i)).toBeVisible()
    await page.getByLabel('Paste delay', { exact: true }).fill('250')
    await page.getByLabel('Paste delay', { exact: true }).press('Tab')
    await expect.poll(() => page.evaluate(async () => (await window.sotto!.getSettings()).pasteDelayMs)).toBe(250)
    await page.getByRole('link', { name: 'Agents', exact: true }).click()
    const coordinator = page.locator('#settings-agents')
    await expect(coordinator.getByLabel('Reasoning account', { exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/account.png' })
    await coordinator.getByLabel('Reasoning account', { exact: true }).selectOption('openrouter')
    await coordinator.getByLabel('Reasoning API key', { exact: true }).fill('fixture-only-key')
    await coordinator.getByLabel('Reasoning API key', { exact: true }).press('Tab')
    await expect(coordinator.getByRole('button', { name: 'Remove reasoning API key', exact: true })).toBeVisible()
    await coordinator.getByRole('button', { name: 'Remove reasoning API key', exact: true }).click()
    await expect.poll(() => page.evaluate(async () => (await window.sotto!.agents!.get()).credentials.reasoning)).toBe(false)
    await coordinator.getByLabel('Reasoning account', { exact: true }).selectOption('none')
    await page.getByRole('link', { name: 'Help', exact: true }).click()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/help.png' })
    await page.keyboard.press('Control+k')
    await expect(page.getByRole('searchbox', { name: 'Search transcripts' })).toBeFocused()
    await page.getByRole('tab', { name: 'Agents', exact: true }).click()
    await page.getByRole('button', { name: 'Not now', exact: true }).click()
    await page.getByRole('button', { name: 'Connect providers', exact: true }).click()
    await expect(page.getByRole('button', { name: 'New session', exact: true })).toBeEnabled()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/agents.png' })
    await page.getByRole('button', { name: 'violet orb', exact: true }).click()
    await expect.poll(() => page.evaluate(async () => (await window.sotto!.agents!.get()).configuration.orbColor)).toBe('violet')
    await page.getByRole('button', { name: 'New session', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'New thread', exact: true })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-session.png' })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByRole('button', { name: 'Open Workshop', exact: true }).click()
    await page.getByRole('button', { name: 'Manage this thread', exact: true }).click()
    await page.getByLabel('Prompt', { exact: true }).fill('Keep this draft until I explicitly send it.')
    await page.keyboard.press('Escape')
    await page.getByRole('button', { name: 'Open Workshop', exact: true }).click()
    await expect(page.getByLabel('Prompt', { exact: true })).toHaveValue('Keep this draft until I explicitly send it.')
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/session.png' })
    await page.getByRole('button', { name: 'Send it', exact: true }).click()
    await expect(page.getByLabel('Session transcript')).toContainText('Keep this draft until I explicitly send it.')
    await page.keyboard.press('Escape')
    await page.getByRole('link', { name: 'Threads', exact: true }).click()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/threads.png' })
    await page.getByRole('button', { name: 'New thread', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'New thread', exact: true })).toBeVisible()
    await page.getByRole('dialog', { name: 'New thread', exact: true }).getByRole('button', { name: /^Sotto test / }).click()
    await page.getByLabel('Thread name', { exact: true }).fill('Design follow-up')
    await page.getByRole('dialog', { name: 'New thread' }).getByLabel('Thread model', { exact: true }).click()
    await page.getByRole('option', { name: 'Claude Test', exact: true }).click()
    await page.getByRole('button', { name: 'Create thread', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Design follow-up', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Threads', exact: true })).toBeVisible()
  } catch (error) {
    await page.screenshot({ path: 'artifacts/crossing/failure.png' }).catch(() => undefined)
    throw error
  } finally { await closeSotto(launched) }
})
