import { expect, test } from '@playwright/test'
import { closeSotto, launchSotto } from './support/sottoLaunch'

const screenshot = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5FoAAAAASUVORK5CYII=', 'base64')

test('creates a thread in a centered popup, configures it, and sends file and pasted screenshots', async () => {
  const previousFolder = process.env.SOTTO_E2E_PROJECT_DIRECTORY
  process.env.SOTTO_E2E_PROJECT_DIRECTORY = process.cwd()
  const launched = await launchSotto()
  const { page } = launched
  try {
    await page.evaluate(async () => {
      await window.sotto!.updateSettings({ onboardingComplete: true })
      await window.sotto!.agents!.command({ type: 'configure', patch: { enabled: true, speak: false } })
      await window.sotto!.agents!.command({ type: 'connect' })
    })
    await page.reload()
    await page.getByRole('link', { name: 'Threads', exact: true }).click()
    await page.getByRole('button', { name: 'New thread', exact: true }).first().click()
    const dialog = page.getByRole('dialog', { name: 'New thread', exact: true })
    await expect(dialog).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Threads', exact: true })).toBeVisible()
    const centered = await dialog.evaluate(node => {
      const rect = node.getBoundingClientRect()
      return Math.abs(rect.x + rect.width / 2 - innerWidth / 2) < 2 && Math.abs(rect.y + rect.height / 2 - innerHeight / 2) < 2
    })
    expect(centered).toBe(true)
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-thread-picker.png' })
    await dialog.getByRole('button', { name: /Local folder/ }).click()
    await expect(dialog).toContainText(process.cwd())
    await dialog.getByRole('textbox', { name: 'Thread name' }).fill('Screenshot review')
    await dialog.getByRole('combobox', { name: 'Thread model' }).click()
    await expect(page.getByRole('dialog', { name: 'Choose model' })).toBeVisible()
    await page.getByRole('textbox', { name: 'Search models' }).press('Enter')
    await expect(dialog).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-thread-provider-models.png' })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog', { name: 'Choose model' })).toHaveCount(0)
    await expect(dialog).toBeVisible()
    await expect(dialog.getByRole('textbox', { name: 'Thread name' })).toHaveValue('Screenshot review')
    await dialog.getByRole('combobox', { name: 'Thread reasoning' }).selectOption('high')
    await dialog.getByRole('combobox', { name: 'Thread permissions' }).selectOption('approval-required')
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-thread-options.png' })
    await dialog.getByRole('button', { name: 'Create thread' }).click()
    await expect(dialog).toHaveCount(0)
    await expect(page.getByRole('heading', { name: 'Screenshot review', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Threads', exact: true })).toBeVisible()
    expect(await page.evaluate(async () => (await window.sotto!.agents!.get()).assignments)).toHaveLength(0)
    await page.getByRole('combobox', { name: 'Thread model' }).click()
    await expect(page.getByRole('dialog', { name: 'Choose model' })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/composer-provider-models.png' })
    await page.getByRole('option', { name: 'Claude Test', exact: true }).click()
    await page.getByRole('combobox', { name: 'Thread reasoning' }).selectOption('low')
    await expect(page.getByRole('combobox', { name: 'Thread reasoning' })).toHaveValue('low')
    await page.getByRole('combobox', { name: 'Thread permissions' }).selectOption('auto-accept-edits')
    await expect(page.getByRole('combobox', { name: 'Thread permissions' })).toHaveValue('auto-accept-edits')
    await page.getByLabel('Screenshot files').setInputFiles({ name: 'screen.png', mimeType: 'image/png', buffer: screenshot })
    await expect(page.getByRole('img', { name: 'screen.png' })).toBeVisible()
    await page.getByRole('textbox', { name: 'Prompt', exact: true }).fill('Review this screenshot.')
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/thread-screenshot-draft.png' })
    await page.getByRole('button', { name: 'Send prompt', exact: true }).click()
    await expect(page.getByLabel('Thread transcript')).toContainText('screen.png')
    await expect(page.getByRole('textbox', { name: 'Prompt', exact: true })).toHaveValue('')
    await expect(page.getByLabel('Attached screenshots').getByRole('img', { name: 'screen.png' })).toHaveCount(0)
    await expect(page.getByLabel('Thread transcript').getByRole('img', { name: 'screen.png' })).toBeVisible()
    await page.getByRole('button', { name: 'Stop agent', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Stop agent', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Attach screenshots' })).toBeEnabled()
    await expect(page.getByRole('textbox', { name: 'Prompt', exact: true })).toBeEnabled()
    await page.getByRole('textbox', { name: 'Prompt', exact: true }).evaluate((node, base64) => {
      const bytes = Uint8Array.from(atob(base64), char => char.charCodeAt(0))
      const data = new DataTransfer()
      data.items.add(new File([bytes], 'pasted.png', { type: 'image/png' }))
      node.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }))
    }, screenshot.toString('base64'))
    await expect(page.getByRole('img', { name: 'pasted.png' })).toBeVisible()
    await page.getByRole('button', { name: 'Send prompt', exact: true }).click()
    await expect(page.getByLabel('Thread transcript')).toContainText('pasted.png')
    // Pending transcript content appears before the native delivery receipt clears the draft.
    await expect(page.getByLabel('Attached screenshots').getByRole('img', { name: 'pasted.png' })).toHaveCount(0)
    await expect(page.getByLabel('Thread transcript').getByRole('img', { name: 'pasted.png' })).toBeVisible()
    const state = await page.evaluate(async () => window.sotto!.agents!.get())
    const created = state.host.threads.find(thread => thread.id === state.activeThreadId)!
    expect(created.messages.filter(message => message.role === 'user')).toHaveLength(2)
    expect(created.messages.at(-1)).toMatchObject({ text: '', attachments: [{ name: 'pasted.png' }] })
    expect(state.assignments).toHaveLength(0)
    await page.getByRole('button', { name: 'Stop agent', exact: true }).click()
    await page.getByRole('button', { name: 'Manage', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Send it', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Attach screenshots' })).toBeEnabled()
    await page.getByLabel('Screenshot files').setInputFiles({ name: 'managed.png', mimeType: 'image/png', buffer: screenshot })
    await expect(page.getByRole('img', { name: 'managed.png' })).toBeVisible()
    await page.evaluate(async () => window.sottoE2E!.agentEvent!({ type: 'reject', threadId: (await window.sotto!.agents!.get()).activeThreadId!, text: 'Temporary provider failure' }))
    await page.getByRole('button', { name: 'Send it', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Temporary provider failure')
    await expect(page.getByRole('img', { name: 'managed.png' })).toBeVisible()
    await page.getByRole('button', { name: 'Send it', exact: true }).click()
    await expect(page.getByLabel('Thread transcript')).toContainText('managed.png')
    await expect(page.getByLabel('Attached screenshots').getByRole('img', { name: 'managed.png' })).toHaveCount(0)
    await expect(page.getByLabel('Thread transcript').getByRole('img', { name: 'managed.png' })).toBeVisible()
  } finally {
    if (previousFolder === undefined) delete process.env.SOTTO_E2E_PROJECT_DIRECTORY
    else process.env.SOTTO_E2E_PROJECT_DIRECTORY = previousFolder
    await closeSotto(launched)
  }
})
