import { expect, test } from '@playwright/test'
import { closeSotto, launchSotto, launchSottoWithVoice, openThreads, paneMenuAction, resizeWindow } from './support/sottoLaunch'

const screenshot = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5FoAAAAASUVORK5CYII=', 'base64')

test('creates a project thread while the hidden coordinator retains another thread draft', async () => {
  const launched = await launchSotto()
  const { page } = launched
  try {
    await page.evaluate(async () => {
      await window.sotto!.updateSettings({ onboardingComplete: true })
      await window.sotto!.agents!.command({ type: 'configure', patch: { enabled: true, speak: false } })
      await window.sotto!.agents!.command({ type: 'connect' })
      await window.sotto!.agents!.command({ type: 'select-thread', threadId: 'workshop' })
      await window.sotto!.agents!.command({ type: 'compose', text: 'Keep the other thread draft' })
      await window.sotto!.agents!.command({ type: 'select-thread', threadId: 'docs' })
    })
    await page.reload()
    await openThreads(page)
    await expect(page.getByRole('textbox', { name: 'Prompt', exact: true })).toHaveValue('')
    expect(await page.evaluate(async () => (await window.sotto!.getSettings()).voiceCoordinatorEnabled)).toBe(false)
    await page.getByRole('button', { name: 'New thread in Sotto test', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'New thread', exact: true })
    await dialog.getByRole('textbox', { name: 'Thread name' }).fill('New project thread')
    await dialog.getByRole('button', { name: 'Create thread' }).click()
    await expect(dialog).toHaveCount(0)
    await expect(page.getByRole('heading', { name: 'New project thread', exact: true })).toBeVisible()
    await expect(page.getByRole('textbox', { name: 'Prompt', exact: true })).toBeEnabled()
    // The optimistic pane appears before main confirms creation and activation.
    await expect.poll(async () => page.evaluate(async () => {
      const state = await window.sotto!.agents!.get()
      return !state.globalLaneBusy && state.host.threads.some(thread => thread.id === state.activeThreadId && thread.title === 'New project thread')
    })).toBe(true)
    const state = await page.evaluate(async () => window.sotto!.agents!.get())
    expect(state.error).toBeNull()
    expect(state.host.threads).toContainEqual(expect.objectContaining({ id: state.activeThreadId, title: 'New project thread' }))
    expect(state).toMatchObject({ draft: 'Keep the other thread draft', draftThreadId: 'workshop', assignments: [] })
    await page.getByRole('textbox', { name: 'Prompt', exact: true }).fill('Only send this new prompt')
    await page.getByRole('button', { name: 'Send prompt', exact: true }).click()
    await expect(page.getByLabel('Thread transcript')).toContainText('Only send this new prompt')
    await expect(page.getByRole('textbox', { name: 'Prompt', exact: true })).toHaveValue('')
    expect(await page.evaluate(async () => window.sotto!.agents!.get())).toMatchObject({ draft: 'Keep the other thread draft', draftThreadId: 'workshop' })
    await page.screenshot({ animations: 'disabled', path: 'artifacts/new-thread-saved-draft/created-and-sent.png' })
  } finally { await closeSotto(launched) }
})

test('creates a thread in a centered popup, configures it, and sends file and pasted screenshots', async () => {
  const previousFolder = process.env.SOTTO_E2E_PROJECT_DIRECTORY
  process.env.SOTTO_E2E_PROJECT_DIRECTORY = process.cwd()
  const launched = await launchSottoWithVoice()
  const { page } = launched
  try {
    await page.evaluate(async () => {
      await window.sotto!.updateSettings({ onboardingComplete: true })
      await window.sotto!.agents!.command({ type: 'configure', patch: { enabled: true, speak: false } })
      await window.sotto!.agents!.command({ type: 'connect' })
    })
    await page.reload()
    await openThreads(page)
    await page.getByRole('button', { name: 'New thread', exact: true }).first().click()
    const dialog = page.getByRole('dialog', { name: 'New thread', exact: true })
    await expect(dialog).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Threads', exact: true })).toBeAttached()
    const centered = await dialog.evaluate(node => {
      const rect = node.getBoundingClientRect()
      return Math.abs(rect.x + rect.width / 2 - innerWidth / 2) < 2 && Math.abs(rect.y + rect.height / 2 - innerHeight / 2) < 2
    })
    expect(centered).toBe(true)
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-thread-picker.png' })
    await dialog.getByRole('button', { name: /Local folder/ }).click()
    await expect(dialog).toContainText(process.cwd())
    await dialog.getByRole('textbox', { name: 'Thread name' }).fill('Screenshot review')
    await dialog.getByRole('combobox', { name: 'Thread model' }).click()
    await expect(page.getByRole('dialog', { name: 'Choose model' })).toBeVisible()
    await page.getByRole('textbox', { name: 'Search models' }).press('Enter')
    await expect(dialog).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-thread-provider-models.png' })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog', { name: 'Choose model' })).toHaveCount(0)
    await expect(dialog).toBeVisible()
    await expect(dialog.getByRole('textbox', { name: 'Thread name' })).toHaveValue('Screenshot review')
    await dialog.getByRole('combobox', { name: 'Thread reasoning' }).selectOption('high')
    await dialog.getByRole('combobox', { name: 'Thread permissions' }).selectOption('approval-required')
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/new-thread-options.png' })
    await dialog.getByRole('button', { name: 'Create thread' }).click()
    await expect(dialog).toHaveCount(0)
    await expect(page.getByRole('heading', { name: 'Screenshot review', exact: true })).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Threads', exact: true })).toBeAttached()
    expect(await page.evaluate(async () => (await window.sotto!.agents!.get()).assignments)).toHaveLength(0)
    await page.getByRole('combobox', { name: 'Thread model' }).click()
    await expect(page.getByRole('dialog', { name: 'Choose model' })).toBeVisible()
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/composer-provider-models.png' })
    // At the 820x560 minimum the chips and the open menu stay inside the window.
    await resizeWindow(launched, 820, 560)
    await expect(page.getByRole('dialog', { name: 'Choose model' })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/composer-chips-820.png' })
    await resizeWindow(launched, 1280, 800)
    await page.getByRole('option', { name: 'Claude Test', exact: true }).click()
    await page.getByRole('combobox', { name: 'Thread reasoning' }).click()
    // The card has no level buttons: Home is the lowest level the model reports.
    await page.getByRole('slider', { name: 'Thread reasoning effort', exact: true }).press('Home')
    await expect(page.getByRole('combobox', { name: 'Thread reasoning' })).toHaveText('Low')
    await page.keyboard.press('Escape')
    await page.getByRole('combobox', { name: 'Thread permissions' }).click()
    await page.getByRole('option', { name: 'Allow edits', exact: true }).click()
    await expect(page.getByRole('combobox', { name: 'Thread permissions' })).toHaveText('Allow edits')
    await page.getByLabel('Screenshot files').setInputFiles({ name: 'screen.png', mimeType: 'image/png', buffer: screenshot })
    await expect(page.getByRole('img', { name: 'screen.png' })).toBeVisible()
    await page.getByRole('textbox', { name: 'Prompt', exact: true }).fill('Review this screenshot.')
    await page.screenshot({ animations: 'disabled', path: 'artifacts/crossing/thread-screenshot-draft.png' })
    await page.getByRole('button', { name: 'Send prompt', exact: true }).click()
    await expect(page.getByLabel('Thread transcript')).toContainText('screen.png')
    await expect(page.getByRole('textbox', { name: 'Prompt', exact: true })).toHaveValue('')
    await expect(page.getByLabel('Attached screenshots').getByRole('img', { name: 'screen.png' })).toHaveCount(0)
    await expect(page.getByLabel('Thread transcript').getByRole('img', { name: 'screen.png' })).toBeVisible()
    await page.getByRole('button', { name: 'Stop agent', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Stop agent', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Attach screenshots' })).toBeEnabled()
    await expect(page.getByRole('textbox', { name: 'Prompt', exact: true })).toBeEnabled()
    await page.getByRole('textbox', { name: 'Prompt', exact: true }).evaluate((node, base64) => {
      const bytes = Uint8Array.from(atob(base64), char => char.charCodeAt(0))
      const data = new DataTransfer()
      data.items.add(new File([bytes], 'pasted.png', { type: 'image/png' }))
      node.dispatchEvent(new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }))
    }, screenshot.toString('base64'))
    await expect(page.getByRole('img', { name: 'pasted.png' })).toBeVisible()
    await page.getByRole('button', { name: 'Send prompt', exact: true }).click()
    await expect(page.getByLabel('Thread transcript')).toContainText('pasted.png')
    // Pending transcript content appears before the native delivery receipt clears the draft.
    await expect(page.getByLabel('Attached screenshots').getByRole('img', { name: 'pasted.png' })).toHaveCount(0)
    await expect(page.getByLabel('Thread transcript').getByRole('img', { name: 'pasted.png' })).toBeVisible()
    const state = await page.evaluate(async () => window.sotto!.agents!.get())
    // The shell summarises histories; the detail bridge carries the messages themselves.
    const created = (await page.evaluate(async id => window.sotto!.agents!.threadDetail!(id), state.activeThreadId!))!
    expect(created.messages.filter(message => message.role === 'user')).toHaveLength(2)
    expect(created.messages.at(-1)).toMatchObject({ text: '', attachments: [{ name: 'pasted.png' }] })
    expect(state.assignments).toHaveLength(0)
    await page.getByRole('button', { name: 'Stop agent', exact: true }).click()
    await paneMenuAction(page, 'Manage')
    await expect(page.getByRole('button', { name: 'Send it', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Attach screenshots' })).toBeEnabled()
    await page.getByLabel('Screenshot files').setInputFiles({ name: 'managed.png', mimeType: 'image/png', buffer: screenshot })
    await expect(page.getByRole('img', { name: 'managed.png' })).toBeVisible()
    await page.evaluate(async () => window.sottoE2E!.agentEvent!({ type: 'reject', threadId: (await window.sotto!.agents!.get()).activeThreadId!, text: 'Temporary provider failure' }))
    await page.getByRole('button', { name: 'Send it', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('Temporary provider failure')
    await expect(page.getByRole('img', { name: 'managed.png' })).toBeVisible()
    await page.getByRole('button', { name: 'Send it', exact: true }).click()
    await expect(page.getByLabel('Thread transcript')).toContainText('managed.png')
    await expect(page.getByLabel('Attached screenshots').getByRole('img', { name: 'managed.png' })).toHaveCount(0)
    await expect(page.getByLabel('Thread transcript').getByRole('img', { name: 'managed.png' })).toBeVisible()
  } finally {
    if (previousFolder === undefined) delete process.env.SOTTO_E2E_PROJECT_DIRECTORY
    else process.env.SOTTO_E2E_PROJECT_DIRECTORY = previousFolder
    await closeSotto(launched)
  }
})
