// @vitest-environment node

import { lstat, mkdir, readFile, rename, rm, symlink, unlink, writeFile } from 'node:fs/promises'

import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { runWorktreeGit as git, ThreadWorktrees } from '../../src/main/agents/threadWorktrees'

import { fixture, removeTestCheckout } from '../fixtures/threadWorktreeFixture'

describe("independent working-copy allocation", () => {
  it('reclaims a clean worktree, keeps its branch, and restore puts the folder back on it', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await git(a.path!, ['checkout', '-b', 'feat/finished'])
    await writeFile(join(a.path!, 'tracked.txt'), 'finished work')
    await git(a.path!, ['add', '.'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Finish'])
    await mkdir(join(a.path!, 'node_modules', 'dep'), { recursive: true }); await writeFile(join(a.path!, 'node_modules', 'dep', 'index.js'), '')
    await writeFile(join(a.path!, '.gitignore'), 'node_modules/\n'); await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore deps'])
    const tip = (await git(f.project, ['rev-parse', 'feat/finished'])).trim()
    const recorded = await f.service.inspect(a)
    expect(await f.service.reclaimFacts(recorded)).toMatchObject({ branch: 'feat/finished', dirty: false, ignored: [], outsideLink: undefined })
    const reclaimed = await f.service.reclaim(recorded, { automatic: true })
    expect(reclaimed).toMatchObject({ status: 'ready', branch: 'feat/finished', path: a.path })
    expect(reclaimed.reclaimedAt).toBeTruthy()
    await expect(lstat(a.path!)).rejects.toThrow()
    expect((await git(f.project, ['rev-parse', 'feat/finished'])).trim()).toBe(tip)
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(1)
    // Nothing else in the repository moved.
    expect(await readFile(join(f.project, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    const restored = await f.service.inspect(await f.service.restore(reclaimed))
    expect(restored).toMatchObject({ status: 'ready', branch: 'feat/finished', reclaimedAt: undefined })
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('finished work')
  })
  it('discards uncommitted work only after the user answers, and never for a rule', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, 'tracked.txt'), 'unsaved')
    await expect(f.service.reclaim(a)).rejects.toThrow('confirm it first')
    await expect(f.service.reclaim(a, { automatic: true, withUncommittedChanges: true })).rejects.toThrow()
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('unsaved')
    expect((await f.service.reclaim(a, { withUncommittedChanges: true })).reclaimedAt).toBeTruthy()
    await expect(lstat(a.path!)).rejects.toThrow()
  })
  it('leaves a folder alone when a rule finds ignored files besides dependencies, a link out of it, or no branch', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), 'node_modules/\nout/\n'); await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore'])
    await mkdir(join(a.path!, 'out')); await writeFile(join(a.path!, 'out', 'bundle.js'), '')
    expect((await f.service.reclaimFacts(a)).ignored).toEqual(['out/'])
    await expect(f.service.reclaim(a, { automatic: true })).rejects.toThrow('besides installed dependencies')
    // A link that leads out of the folder could be followed by the removal; the real folder behind it must stay whole.
    const shared = join(f.root, 'shared-deps'); await mkdir(shared); await writeFile(join(shared, 'keep.txt'), 'real install')
    await symlink(shared, join(a.path!, 'node_modules'), 'junction')
    expect((await f.service.reclaimFacts(a)).outsideLink).toBe('node_modules')
    await expect(f.service.reclaim(a, { withUncommittedChanges: true })).rejects.toThrow('link to another folder')
    expect(await readFile(join(shared, 'keep.txt'), 'utf8')).toBe('real install')
    await rm(join(a.path!, 'node_modules'), { recursive: false }).catch(() => unlink(join(a.path!, 'node_modules')))
    await rm(join(a.path!, 'out'), { recursive: true })
    await git(a.path!, ['checkout', '--detach'])
    await expect(f.service.reclaim(a)).rejects.toThrow('no branch checked out')
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    await expect(f.service.reclaim({ mode: 'shared', status: 'ready', path: f.project })).rejects.toThrow('shared or reused folder stays')
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(2)
  })
  it('requires the exact ignored file list and refuses new files added after the confirmation', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), '.env\nlocal/\nnode_modules/\n')
    await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore local files'])
    const empty = await f.service.reclaimFacts(a)
    await writeFile(join(a.path!, '.env'), 'keep this secret')
    await mkdir(join(a.path!, 'local'))
    await writeFile(join(a.path!, 'local', 'data.txt'), 'local data')
    const facts = await f.service.reclaimFacts(a)
    expect(facts).toMatchObject({ dirty: false, ignored: ['.env', 'local/'] })
    await expect(f.service.reclaim(a)).rejects.toThrow('holds ignored files')
    await expect(f.service.reclaim(a, { confirmedItems: empty.items, confirmedIgnored: empty.ignored })).rejects.toThrow('ignored items changed')
    await expect(f.service.reclaim(a, { automatic: true, confirmedItems: facts.items, confirmedIgnored: facts.ignored })).rejects.toThrow('besides installed dependencies')
    await writeFile(join(a.path!, 'another.env'), 'new local work')
    await writeFile(join(a.path!, '.gitignore'), '.env\nanother.env\nlocal/\nnode_modules/\n')
    await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore another file'])
    await expect(f.service.reclaim(a, { confirmedItems: facts.items, confirmedIgnored: facts.ignored })).rejects.toThrow('ignored items changed')
    expect(await readFile(join(a.path!, '.env'), 'utf8')).toBe('keep this secret')
    const refreshed = await f.service.reclaimFacts(a)
    expect((await f.service.reclaim(a, { confirmedItems: refreshed.items, confirmedIgnored: refreshed.ignored })).reclaimedAt).toBeTruthy()
  })
  it.each([
    ['repository', true], ['worktree', true], ['repository', false], ['worktree', false],
  ] as const)('lists a nested %s (ignored: %s) and removes it only with the tick', async (kind, ignored) => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), ignored ? '.worktrees/\n' : '')
    await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore nested folders'])
    const nested = join(a.path!, '.worktrees', 'n')
    await mkdir(nested, { recursive: true })
    if (kind === 'repository') await git(nested, ['init'])
    else await git(f.project, ['worktree', 'add', '-b', 'nested', '--', nested, 'HEAD'])
    await writeFile(join(nested, 'unsaved.txt'), 'nested uncommitted work')
    const facts = await f.service.reclaimFacts(a)
    expect(facts.ignored).toEqual(ignored ? ['.worktrees/', '.worktrees/n/'] : ['.worktrees/n/'])
    expect(facts.repositories).toEqual([{ path: '.worktrees/n/', changeCount: 1, ...(kind === 'repository' ? { unpushedCommitCount: 0 } : {}), kind }])
    await expect(f.service.reclaim(a, { withUncommittedChanges: true })).rejects.toThrow('holds ignored files')
    await expect(f.service.reclaim(a, { withUncommittedChanges: true, confirmedItems: facts.items, confirmedIgnored: facts.ignored })).rejects.toThrow('nested work changed')
    expect(await readFile(join(nested, 'unsaved.txt'), 'utf8')).toBe('nested uncommitted work')
    expect((await f.service.reclaim(a, { withUncommittedChanges: true, confirmedItems: facts.items, confirmedIgnored: facts.ignored, confirmedRepositories: facts.repositories })).reclaimedAt).toBeTruthy()
    await expect(lstat(nested)).rejects.toMatchObject({ code: 'ENOENT' })
  })
  it.each(['added', 'removed', 'rewritten'])('checks file counts inside the confirmed ignored folder (%s)', async change => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), 'dist/\n')
    await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore cache'])
    await mkdir(join(a.path!, 'dist'))
    await writeFile(join(a.path!, 'dist', 'one.js'), '1234')
    const facts = await f.service.reclaimFacts(a)
    expect(facts.ignored).toEqual(['dist/'])
    expect(facts.items).toEqual([{ path: 'dist/', bytes: 4, fileCount: 1 }])
    if (change === 'added') await writeFile(join(a.path!, 'dist', 'two.js'), 'unseen work')
    else if (change === 'removed') await unlink(join(a.path!, 'dist', 'one.js'))
    else await writeFile(join(a.path!, 'dist', 'one.js'), 'a rewritten cache with a different size')
    const removal = f.service.reclaim(a, { confirmedItems: facts.items, confirmedIgnored: facts.ignored })
    if (change === 'rewritten') expect((await removal).reclaimedAt).toBeTruthy()
    else {
      await expect(removal).rejects.toThrow('The folder changed. Nothing was removed. Choose Remove worktree again to see the new list.')
      expect((await lstat(a.path!)).isDirectory()).toBe(true)
      if (change === 'added') expect(await readFile(join(a.path!, 'dist', 'two.js'), 'utf8')).toBe('unseen work')
      const refreshed = await f.service.reclaimFacts(a)
      expect((await f.service.reclaim(a, { confirmedItems: refreshed.items, confirmedIgnored: refreshed.ignored })).reclaimedAt).toBeTruthy()
    }
  })
  it('refuses files appearing inside an ignored folder after the first reclaim observation', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), '.local/\n')
    await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore local files'])
    await mkdir(join(a.path!, '.local'))
    await writeFile(join(a.path!, '.local', 'cache.txt'), 'cache')
    const preview = await f.service.reclaimFacts(a)
    let reads = 0
    const service = new ThreadWorktrees(f.root, async (cwd, args) => {
      if (cwd === a.path && args.includes('--ignored') && ++reads === 2) await writeFile(join(a.path!, '.local', 'secret.txt'), 'unseen secret')
      return git(cwd, args)
    })
    await expect(service.reclaim(a, { confirmedIgnored: preview.ignored, confirmedItems: preview.items })).rejects.toThrow('The folder changed')
    expect(await readFile(join(a.path!, '.local', 'secret.txt'), 'utf8')).toBe('unseen secret')
  })
  it.each(['containing', 'separate'])('clears removed nested worktree registrations in the %s repository', async owner => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    const repository = owner === 'containing' ? f.project : join(f.root, 'other')
    if (owner === 'separate') await git(f.root, ['clone', '--', f.project, repository])
    const nested = join(a.path!, 'nested')
    await git(repository, ['worktree', 'add', '-b', 'nested', '--', nested, 'HEAD'])
    await writeFile(join(nested, 'unsaved.txt'), 'nested work')
    const otherMissing = join(f.root, 'other-missing')
    await git(repository, ['worktree', 'add', '-b', 'missing', '--', otherMissing, 'HEAD'])
    await removeTestCheckout(f.root, otherMissing)
    const preview = await f.service.reclaimFacts(a)
    expect((await f.service.reclaim(a, { withUncommittedChanges: true, confirmedItems: preview.items, confirmedIgnored: preview.ignored, confirmedRepositories: preview.repositories })).reclaimedAt).toBeTruthy()
    const registrations = await git(repository, ['worktree', 'list', '--porcelain'])
    expect(registrations).not.toContain('refs/heads/nested')
    expect(registrations).toContain('refs/heads/missing')
    expect((await git(repository, ['branch', '--list', 'nested'])).trim()).toBe('nested')
    const replacement = join(f.root, 'replacement')
    await git(repository, ['worktree', 'add', '--', replacement, 'nested'])
    expect((await lstat(replacement)).isDirectory()).toBe(true)
  })
  it('preserves a nested worktree locked after its preview', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    const nested = join(a.path!, 'nested')
    await git(f.project, ['worktree', 'add', '-b', 'nested', '--', nested, 'HEAD'])
    const preview = await f.service.reclaimFacts(a)
    await git(f.project, ['worktree', 'lock', '--', nested])
    await expect(f.service.reclaim(a, { withUncommittedChanges: true, confirmedItems: preview.items, confirmedIgnored: preview.ignored, confirmedRepositories: preview.repositories })).rejects.toThrow('A nested worktree is locked. Nothing was removed.')
    expect((await lstat(nested)).isDirectory()).toBe(true)
    expect(await git(f.project, ['worktree', 'list', '--porcelain'])).toContain('refs/heads/nested')
    await git(f.project, ['worktree', 'unlock', '--', nested])
    const refreshed = await f.service.reclaimFacts(a)
    expect((await f.service.reclaim(a, { withUncommittedChanges: true, confirmedItems: refreshed.items, confirmedIgnored: refreshed.ignored, confirmedRepositories: refreshed.repositories })).reclaimedAt).toBeTruthy()
    expect(await git(f.project, ['worktree', 'list', '--porcelain'])).not.toContain('refs/heads/nested')
  })
  it('refuses an unseen ignored file inside a confirmed nested repository row', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    const nested = join(a.path!, 'nested'); await mkdir(nested); await git(nested, ['init'])
    await writeFile(join(nested, '.gitignore'), '*.secret\n')
    const preview = await f.service.reclaimFacts(a)
    expect(preview.items.find(item => item.path === 'nested/')?.fileCount).toBeGreaterThan(0)
    await writeFile(join(nested, 'unseen.secret'), 'keep this')
    const latest = await f.service.reclaimFacts(a)
    expect(latest.repositories).toEqual(preview.repositories)
    await expect(f.service.reclaim(a, { withUncommittedChanges: true, confirmedItems: preview.items, confirmedIgnored: preview.ignored, confirmedRepositories: preview.repositories })).rejects.toThrow('The folder changed')
    expect(await readFile(join(nested, 'unseen.secret'), 'utf8')).toBe('keep this')
  })
  it.each(['branch', 'tag', 'bare'])('counts unpublished nested history outside HEAD (%s)', async reference => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    const nested = join(a.path!, 'nested')
    await git(a.path!, ['clone', '--', f.project, nested])
    await git(nested, ['checkout', '-b', 'private'])
    await writeFile(join(nested, 'private.txt'), 'unpublished history')
    await git(nested, ['add', '.'])
    await git(nested, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Private'])
    if (reference === 'tag') await git(nested, ['tag', 'private-save'])
    await git(nested, ['checkout', '-'])
    if (reference === 'tag') await git(nested, ['branch', '-D', 'private'])
    if (reference === 'bare') {
      const bare = join(f.root, 'bare')
      await git(f.root, ['clone', '--bare', '--', nested, bare])
      await removeTestCheckout(f.root, nested)
      await rename(bare, nested)
      await git(nested, ['update-ref', 'refs/remotes/origin/main', (await git(f.project, ['rev-parse', 'HEAD'])).trim()])
      await git(nested, ['symbolic-ref', 'HEAD', 'refs/heads/unborn'])
    }
    const preview = await f.service.reclaimFacts(a)
    expect(preview.repositories.find(item => item.kind === 'repository')?.unpushedCommitCount).toBe(1)
  })
  it.each(['none', 'some', 'all'])('counts nested repository commits not on a remote (%s published)', async published => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    const nested = join(a.path!, 'nested'); await mkdir(nested); await git(nested, ['init'])
    await writeFile(join(nested, 'saved.txt'), 'first')
    await git(nested, ['add', '.'])
    await git(nested, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'First'])
    const first = (await git(nested, ['rev-parse', 'HEAD'])).trim()
    await writeFile(join(nested, 'saved.txt'), 'second')
    await git(nested, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-am', 'Second'])
    if (published !== 'none') {
      await git(nested, ['remote', 'add', 'origin', f.project])
      await git(nested, ['update-ref', 'refs/remotes/origin/main', published === 'some' ? first : 'HEAD'])
    }
    const preview = await f.service.reclaimFacts(a)
    expect(preview.repositories).toEqual([{ path: 'nested/', changeCount: 0, kind: 'repository', unpushedCommitCount: published === 'none' ? 2 : published === 'some' ? 1 : 0 }])
  })
  it.each(['ignored', 'untracked'])('refuses a new %s path added during the final filesystem walk', async kind => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), '*.env\n.cache/\n')
    await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore secrets'])
    const nested = join(a.path!, '.cache', 'nested'); await mkdir(nested, { recursive: true }); await git(nested, ['init'])
    const preview = await f.service.reclaimFacts(a)
    let reads = 0
    const service = new ThreadWorktrees(f.root, async (cwd, args) => {
      // Both early ls-files calls have completed by the time the walk enters this repository.
      if (cwd === nested && args[0] === 'status' && ++reads === 2) await writeFile(join(a.path!, kind === 'ignored' ? 'new.env' : 'unsaved.txt'), 'keep me')
      return git(cwd, args)
    })
    await expect(service.reclaim(a, { confirmedItems: preview.items, confirmedIgnored: preview.ignored, confirmedRepositories: preview.repositories })).rejects.toThrow('files changed')
    expect(await readFile(join(a.path!, kind === 'ignored' ? 'new.env' : 'unsaved.txt'), 'utf8')).toBe('keep me')
  })

  it('lists a bare repository hidden inside dependencies and requires the tick', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), 'node_modules/\n')
    await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore dependencies'])
    const nested = join(a.path!, 'node_modules', 'local.git'); await mkdir(nested, { recursive: true })
    await git(nested, ['init', '--bare'])
    const facts = await f.service.reclaimFacts(a)
    expect(facts.repositories).toEqual([{ path: 'node_modules/local.git/', changeCount: 0, unpushedCommitCount: 0, kind: 'repository' }])
    await expect(f.service.reclaim(a, { automatic: true })).rejects.toThrow('besides installed dependencies')
    expect((await f.service.reclaim(a, { confirmedItems: facts.items, confirmedIgnored: facts.ignored, confirmedRepositories: facts.repositories })).reclaimedAt).toBeTruthy()
  })
})
