export const TRANSCRIPTION_SAMPLE_RATE = 16_000 as const
export const MAX_TRANSCRIPTION_SECONDS = 300 as const
export const MAX_TRANSCRIPTION_SAMPLES =
  TRANSCRIPTION_SAMPLE_RATE * MAX_TRANSCRIPTION_SECONDS
