// @vitest-environment node
import { lstat, mkdir, mkdtemp, readFile, rm, symlink, unlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { runWorktreeGit as git, ThreadWorktrees } from '../../../src/main/agents/threadWorktrees'
import { resolveThreadWorkingDirectory } from '../../../src/shared/threadWorkingDirectory'

const roots: string[] = []
afterEach(async () => {
  for (const root of roots.splice(0)) {
    if (dirname(resolve(root)) !== resolve(tmpdir()) || !root.includes('sotto-worktree-test-')) throw new Error('Unsafe fixture cleanup')
    await rm(root, { recursive: true, force: true })
  }
})
async function fixture(commit = true) {
  const root = await mkdtemp(join(tmpdir(), 'sotto-worktree-test-')); roots.push(root)
  const project = join(root, 'project'); await mkdir(project)
  await git(project, ['init'])
  if (commit) {
    await writeFile(join(project, 'tracked.txt'), 'committed baseline')
    await git(project, ['add', '.'])
    await git(project, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Baseline'])
  }
  return { root, project, service: new ThreadWorktrees(root) }
}
/** Removes only a test-owned checkout under the fixture root; the production implementation has no removal path. */
async function removeTestCheckout(root: string, path: string) {
  expect(resolve(path).startsWith(resolve(root) + '\\') || resolve(path).startsWith(resolve(root) + '/')).toBe(true)
  await rm(path, { recursive: true })
}
describe('independent working-copy allocation', () => {
  it('isolates concurrent allocations from a dirty source and retains user edits on reuse', async () => {
    const f = await fixture()
    await writeFile(join(f.project, 'tracked.txt'), 'source user edits')
    const [a, b] = await Promise.all([f.service.allocate(f.project, 'independent'), f.service.allocate(f.project, 'independent')])
    expect(a.branch).not.toBe(b.branch); expect(a.path).not.toBe(b.path)
    const [first, second] = await Promise.all([f.service.ensure(a), f.service.ensure(b)])
    expect(await readFile(join(first.path!, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    await writeFile(join(first.path!, 'tracked.txt'), 'first edits')
    await writeFile(join(second.path!, 'tracked.txt'), 'second edits')
    expect(await readFile(join(f.project, 'tracked.txt'), 'utf8')).toBe('source user edits')
    expect((await new ThreadWorktrees(f.root).ensure(a)).dirty).toBe(true)
    expect(await readFile(join(first.path!, 'tracked.txt'), 'utf8')).toBe('first edits')
    expect(await readFile(join(second.path!, 'tracked.txt'), 'utf8')).toBe('second edits')
  })
  it('recovers a lost Git acknowledgement by checking exact registration before any retry', async () => {
    const f = await fixture(); const allocation = await f.service.allocate(f.project, 'independent')
    const flaky = new ThreadWorktrees(f.root, async (cwd, args) => {
      const result = await git(cwd, args)
      if (args.includes('add')) throw new Error('Lost acknowledgement')
      return result
    })
    await expect(flaky.ensure(allocation)).rejects.toThrow('Lost acknowledgement')
    expect((await f.service.ensure(allocation)).status).toBe('ready')
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(2)
  })
  it('keeps existing paths and branches untouched', async () => {
    const f = await fixture(); const pathCollision = await f.service.allocate(f.project, 'independent')
    await mkdir(pathCollision.path!, { recursive: true }); await writeFile(join(pathCollision.path!, 'user.txt'), 'keep')
    await expect(f.service.ensure(pathCollision)).rejects.toThrow('already exists')
    expect(await readFile(join(pathCollision.path!, 'user.txt'), 'utf8')).toBe('keep')
    const branchCollision = await f.service.allocate(f.project, 'independent')
    await git(f.project, ['branch', branchCollision.branch!])
    await expect(f.service.ensure(branchCollision)).rejects.toThrow('already exists')
    expect((await git(f.project, ['rev-parse', branchCollision.branch!])).trim()).toBe(branchCollision.baseCommit)
  })
  it('follows the branch a worktree has checked out and refuses only a folder that is not its checkout', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await git(a.path!, ['checkout', '-b', 'user-chosen-branch'])
    // Both the send path and Retry setup follow the branch the folder is on.
    expect(await f.service.inspect(a)).toMatchObject({ status: 'ready', branch: 'user-chosen-branch' })
    expect(await f.service.ensure(a)).toMatchObject({ status: 'ready', branch: 'user-chosen-branch' })
    await git(a.path!, ['checkout', '--detach'])
    const detached = await f.service.inspect(a)
    expect(detached.status).toBe('ready'); expect(detached.branch).toBeUndefined()
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    const elsewhere = join(f.root, 'elsewhere'); await mkdir(elsewhere)
    await expect(f.service.inspect({ ...a, path: elsewhere })).rejects.toThrow('no longer this thread')
  })
  it('switches back to a named branch when the user asks, carrying uncommitted work and refusing anything else', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    const started = a.branch!
    await git(a.path!, ['checkout', '-b', 'feat/agent-chose'])
    await writeFile(join(a.path!, 'tracked.txt'), 'work in progress')
    const restored = await f.service.switchBranch(a, started)
    expect(restored).toMatchObject({ status: 'ready', branch: started, dirty: true })
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('work in progress')
    expect(await f.service.switchBranch(restored, started)).toMatchObject({ branch: started })
    await expect(f.service.switchBranch(a, 'never-made')).rejects.toThrow('no longer exists')
    await expect(f.service.switchBranch(a, '--orphan')).rejects.toThrow('cannot be restored')
    await expect(f.service.switchBranch({ mode: 'shared', status: 'ready', path: f.project }, started)).rejects.toThrow('already used by worktree')
    expect((await f.service.inspect(a)).branch).toBe(started)
  })
  it('chooses the requested base, uses a short temporary branch, and explicitly reuses a registered checkout', async () => {
    const f = await fixture()
    await git(f.project, ['branch', 'chosen-base'])
    await writeFile(join(f.project, 'tracked.txt'), 'new main commit')
    await git(f.project, ['add', '.'])
    await git(f.project, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Main advanced'])
    const allocated = await f.service.allocate(f.project, 'independent', { baseBranch: 'chosen-base' })
    expect(allocated.branch).toMatch(/^sotto\/[a-f0-9]{8}$/u)
    const checkout = await f.service.ensure(allocated)
    expect(await readFile(join(checkout.path!, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    const reused = await f.service.allocate(f.project, 'independent', { existingWorktreePath: checkout.path })
    expect(await f.service.ensure(reused)).toMatchObject({ path: checkout.path, branch: checkout.branch, reused: true })
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(2)
    await expect(f.service.allocate(f.project, 'independent', { baseBranch: 'missing' })).rejects.toThrow('base branch missing is unavailable')
    await expect(f.service.allocate(f.project, 'independent', { baseBranch: 'chosen-base', startFromOrigin: true })).rejects.toThrow('could not be fetched')
  })
  it("checks a pull request's branch out as it stands in a new worktree, with no branch of its own", async () => {
    const f = await fixture()
    await git(f.project, ['branch', 'feat/pr'])
    const allocated = await f.service.allocate(f.project, 'independent', { checkoutBranch: 'feat/pr' })
    expect(allocated).toMatchObject({ status: 'pending', branch: 'feat/pr', checkoutBranch: true, temporaryBranch: false })
    const checkout = await f.service.ensure(allocated)
    expect(checkout).toMatchObject({ status: 'ready', branch: 'feat/pr' })
    expect((await git(checkout.path!, ['branch', '--show-current'])).trim()).toBe('feat/pr')
    expect((await git(f.project, ['branch', '--list', 'sotto/*'])).trim()).toBe('')
    await expect(f.service.allocate(f.project, 'independent', { checkoutBranch: 'gone' })).rejects.toThrow('The branch gone is gone.')
    // The branch is in that folder now, so a second worktree for it is refused rather than forced.
    await expect(f.service.ensure(await f.service.allocate(f.project, 'independent', { checkoutBranch: 'feat/pr' }))).rejects.toThrow('already checked out in another folder')
  })
  it('fetches the explicitly selected origin branch instead of silently using local HEAD', async () => {
    const f = await fixture()
    const remote = join(f.root, 'origin'); await mkdir(remote)
    await git(remote, ['init', '--bare'])
    await git(f.project, ['remote', 'add', 'origin', remote])
    await git(f.project, ['push', 'origin', 'HEAD:refs/heads/base'])
    await git(f.project, ['branch', 'base'])
    await writeFile(join(f.project, 'tracked.txt'), 'local-only commit')
    await git(f.project, ['add', '.'])
    await git(f.project, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Local'])
    await git(f.project, ['branch', '-f', 'base', 'HEAD'])
    const checkout = await f.service.ensure(await f.service.allocate(f.project, 'independent', { baseBranch: 'base', startFromOrigin: true }))
    expect(await readFile(join(checkout.path!, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    expect(checkout).toMatchObject({ baseBranch: 'base', startFromOrigin: true })
    const options = await f.service.options(f.project)
    expect(options.branches).toContain('base')
    expect(options.worktrees).toContainEqual({ path: checkout.path!.replaceAll('\\', '/'), branch: checkout.branch })
  })
  it('lets Git refuse a conflicting shared-checkout restore without losing current edits', async () => {
    const f = await fixture()
    const shared = await f.service.inspect(await f.service.allocate(f.project, 'shared'))
    await git(f.project, ['switch', '-c', 'different'])
    await writeFile(join(f.project, 'tracked.txt'), 'branch changes')
    await git(f.project, ['add', '.'])
    await git(f.project, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Different'])
    await writeFile(join(f.project, 'tracked.txt'), 'unsaved user work')
    await expect(f.service.switchBranch(shared, shared.branch!)).rejects.toThrow()
    expect(await readFile(join(f.project, 'tracked.txt'), 'utf8')).toBe('unsaved user work')
    expect((await f.service.inspect(shared)).branch).toBe('different')
  })
  it('reads and restores a shared checkout branch and clears the branch at detached HEAD', async () => {
    const f = await fixture()
    const shared = await f.service.inspect(await f.service.allocate(f.project, 'shared'))
    await git(f.project, ['switch', '-c', 'next'])
    await writeFile(join(f.project, 'tracked.txt'), 'uncommitted edits')
    expect(await f.service.inspect(shared)).toMatchObject({ branch: 'next', dirty: true })
    expect(await f.service.switchBranch(shared, shared.branch!)).toMatchObject({ branch: shared.branch, dirty: true })
    expect(await readFile(join(f.project, 'tracked.txt'), 'utf8')).toBe('uncommitted edits')
    await git(f.project, ['checkout', '--detach'])
    expect((await f.service.inspect(shared)).branch).toBeUndefined()
  })
  it('renames only a still-temporary worktree branch and preserves an agent-selected branch', async () => {
    const f = await fixture()
    const checkout = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    const named = await f.service.renameTemporaryBranch(checkout, 'sotto/fix-something')
    expect(named).toMatchObject({ branch: 'sotto/fix-something', temporaryBranch: false })
    const next = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await git(next.path!, ['switch', '-c', 'feat/agent-chose'])
    expect(await f.service.renameTemporaryBranch(next, 'sotto/do-not-use')).toMatchObject({ branch: 'feat/agent-chose', temporaryBranch: false })
  })
  it('requires an initial Git commit but permits a deliberate shared empty or non-Git folder', async () => {
    const f = await fixture(false)
    await expect(f.service.allocate(f.project, 'independent')).rejects.toThrow('no commit')
    expect(await f.service.allocate(f.project, 'shared')).toMatchObject({ mode: 'shared', status: 'ready', path: f.project })
    const ordinary = join(f.root, 'ordinary'); await mkdir(ordinary)
    expect(await f.service.allocate(ordinary, 'independent')).toMatchObject({ mode: 'shared', status: 'ready', path: ordinary })
  })
  it('does not silently share after missing Git, permission failures, or an unavailable project', async () => {
    const f = await fixture()
    for (const message of ['Git is unavailable', 'Permission denied']) {
      const unavailable = new ThreadWorktrees(f.root, async () => { throw new Error(message) })
      await expect(unavailable.allocate(f.project, 'independent')).rejects.toThrow(message)
      expect((await unavailable.allocate(f.project, 'shared')).status).toBe('ready')
    }
    await expect(f.service.allocate(join(f.root, 'missing'), 'independent')).rejects.toThrow()
  })
  it('preserves a monorepo project subdirectory and rejects uncommitted-only counterparts until committed', async () => {
    const f = await fixture()
    const app = join(f.project, 'packages', 'app'); await mkdir(app, { recursive: true })
    await writeFile(join(app, 'index.txt'), 'app contents')
    await expect(f.service.allocate(app, 'independent')).rejects.toThrow('not present in the committed source')
    await git(f.project, ['add', '.'])
    await git(f.project, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Add app'])
    const a = await f.service.ensure(await f.service.allocate(app, 'independent'))
    expect(a.projectRelativePath).toBe('packages/app')
    expect(await f.service.workingDirectory(a)).toBe(join(a.path!, 'packages', 'app'))
    expect(await readFile(join(await f.service.workingDirectory(a), 'index.txt'), 'utf8')).toBe('app contents')
  })
  it('inspection does not replace a missing checkout', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await removeTestCheckout(f.root, a.path!)
    await expect(f.service.inspect(a)).rejects.toThrow()
    // A detached checkout records no branch, so there is nothing to recreate it from.
    await expect(f.service.restore({ ...a, branch: undefined })).resolves.toMatchObject({ path: a.path })
    await expect(f.service.ensure({ ...a, branch: undefined })).rejects.toThrow()
  })
  it('recreates a deleted checkout from the branch it recorded, without resetting the branch', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await git(a.path!, ['checkout', '-b', 'user-chosen-branch'])
    await writeFile(join(a.path!, 'tracked.txt'), 'work on the user branch')
    await git(a.path!, ['add', '.'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Work'])
    const recorded = await f.service.inspect(a)
    expect(recorded.branch).toBe('user-chosen-branch')
    const tip = (await git(f.project, ['rev-parse', 'user-chosen-branch'])).trim()
    await removeTestCheckout(f.root, a.path!)
    expect(await f.service.ensure(recorded)).toMatchObject({ status: 'ready', branch: 'user-chosen-branch' })
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('work on the user branch')
    expect((await git(f.project, ['rev-parse', 'user-chosen-branch'])).trim()).toBe(tip)
    expect(await readFile(join(f.project, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(2)
  })
  it('refuses to recreate a checkout whose branch is checked out in another folder and removes nothing', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await git(a.path!, ['checkout', '-b', 'user-chosen-branch'])
    const recorded = await f.service.inspect(a)
    await removeTestCheckout(f.root, a.path!)
    await git(f.project, ['worktree', 'prune'])
    const elsewhere = join(f.root, 'elsewhere')
    await git(f.project, ['worktree', 'add', '--', elsewhere, 'user-chosen-branch'])
    await writeFile(join(elsewhere, 'other.txt'), 'other folder work')
    await expect(f.service.restore(recorded)).rejects.toThrow('elsewhere')
    await expect(f.service.ensure(recorded)).rejects.toThrow('elsewhere')
    expect(await readFile(join(elsewhere, 'other.txt'), 'utf8')).toBe('other folder work')
    expect(await readFile(join(elsewhere, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    expect((await git(f.project, ['rev-parse', 'user-chosen-branch'])).trim()).toBe((await git(elsewhere, ['rev-parse', 'HEAD'])).trim())
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(2)
  })
  it('does not reuse a checkout while Git reports it locked', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await git(f.project, ['worktree', 'lock', '--reason', 'initializing', a.path!])
    await expect(f.service.ensure(a)).rejects.toThrow('locked')
    await expect(f.service.inspect(a)).rejects.toThrow('locked')
    await git(f.project, ['worktree', 'unlock', a.path!])
    expect((await f.service.ensure(a)).status).toBe('ready')
  })
  it('reclaims a clean worktree, keeps its branch, and restore puts the folder back on it', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await git(a.path!, ['checkout', '-b', 'feat/finished'])
    await writeFile(join(a.path!, 'tracked.txt'), 'finished work')
    await git(a.path!, ['add', '.'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Finish'])
    await mkdir(join(a.path!, 'node_modules', 'dep'), { recursive: true }); await writeFile(join(a.path!, 'node_modules', 'dep', 'index.js'), '')
    await writeFile(join(a.path!, '.gitignore'), 'node_modules/\n'); await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore deps'])
    const tip = (await git(f.project, ['rev-parse', 'feat/finished'])).trim()
    const recorded = await f.service.inspect(a)
    expect(await f.service.reclaimFacts(recorded)).toMatchObject({ branch: 'feat/finished', dirty: false, ignored: [], outsideLink: undefined })
    const reclaimed = await f.service.reclaim(recorded, { automatic: true })
    expect(reclaimed).toMatchObject({ status: 'ready', branch: 'feat/finished', path: a.path })
    expect(reclaimed.reclaimedAt).toBeTruthy()
    await expect(lstat(a.path!)).rejects.toThrow()
    expect((await git(f.project, ['rev-parse', 'feat/finished'])).trim()).toBe(tip)
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(1)
    // Nothing else in the repository moved.
    expect(await readFile(join(f.project, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    const restored = await f.service.inspect(await f.service.restore(reclaimed))
    expect(restored).toMatchObject({ status: 'ready', branch: 'feat/finished', reclaimedAt: undefined })
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('finished work')
  })
  it('discards uncommitted work only after the user answers, and never for a rule', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, 'tracked.txt'), 'unsaved')
    await expect(f.service.reclaim(a)).rejects.toThrow('confirm it first')
    await expect(f.service.reclaim(a, { automatic: true, withUncommittedChanges: true })).rejects.toThrow()
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('unsaved')
    expect((await f.service.reclaim(a, { withUncommittedChanges: true })).reclaimedAt).toBeTruthy()
    await expect(lstat(a.path!)).rejects.toThrow()
  })
  it('leaves a folder alone when a rule finds ignored files besides dependencies, a link out of it, or no branch', async () => {
    const f = await fixture(); const a = await f.service.ensure(await f.service.allocate(f.project, 'independent'))
    await writeFile(join(a.path!, '.gitignore'), 'node_modules/\nout/\n'); await git(a.path!, ['add', '.gitignore'])
    await git(a.path!, ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-m', 'Ignore'])
    await mkdir(join(a.path!, 'out')); await writeFile(join(a.path!, 'out', 'bundle.js'), '')
    expect((await f.service.reclaimFacts(a)).ignored).toEqual(['out/'])
    await expect(f.service.reclaim(a, { automatic: true })).rejects.toThrow('besides installed dependencies')
    // A link that leads out of the folder could be followed by the removal; the real folder behind it must stay whole.
    const shared = join(f.root, 'shared-deps'); await mkdir(shared); await writeFile(join(shared, 'keep.txt'), 'real install')
    await symlink(shared, join(a.path!, 'node_modules'), 'junction')
    expect((await f.service.reclaimFacts(a)).outsideLink).toBe('node_modules')
    await expect(f.service.reclaim(a, { withUncommittedChanges: true })).rejects.toThrow('link to another folder')
    expect(await readFile(join(shared, 'keep.txt'), 'utf8')).toBe('real install')
    await rm(join(a.path!, 'node_modules'), { recursive: false }).catch(() => unlink(join(a.path!, 'node_modules')))
    await rm(join(a.path!, 'out'), { recursive: true })
    await git(a.path!, ['checkout', '--detach'])
    await expect(f.service.reclaim(a)).rejects.toThrow('no branch checked out')
    expect(await readFile(join(a.path!, 'tracked.txt'), 'utf8')).toBe('committed baseline')
    await expect(f.service.reclaim({ mode: 'shared', status: 'ready', path: f.project })).rejects.toThrow('shared or reused folder stays')
    expect((await git(f.project, ['worktree', 'list', '--porcelain'])).match(/worktree /gu)).toHaveLength(2)
  })
  it('resolves authoritative cwd before project fallback and blocks unresolved setup', () => {
    expect(resolveThreadWorkingDirectory({ workingDirectory: '/actual' }, { path: '/project' })).toBe('/actual')
    expect(resolveThreadWorkingDirectory({}, { path: '/legacy' })).toBe('/legacy')
    expect(() => resolveThreadWorkingDirectory({ worktree: { mode: 'independent', status: 'error', error: 'setup failed' } }, { path: '/project' })).toThrow('setup failed')
  })
})
