{
  "version": 1,
  "id": "omarchy",
  "name": "Omarchy",
  "appearance": "{{ mode }}",
  "colors": {
    "canvas": "{{ background }}",
    "chrome": "{{ background }}",
    "toolbar": "{{ background }}",
    "toolbarForeground": "{{ foreground }}",
    "toolbarBorder": "{{ mix background foreground 14% }}",
    "toolbarControl": "{{ mix background foreground 6% }}",
    "toolbarControlForeground": "{{ foreground }}",
    "toolbarControlHover": "{{ mix background foreground 10% }}",
    "surface": "{{ mix background foreground 3% }}",
    "surfaceRaised": "{{ mix background foreground 7% }}",
    "surfaceOverlay": "{{ mix background foreground 10% }}",
    "text": "{{ foreground }}",
    "textMuted": "{{ mix foreground background 30% }}",
    "border": "{{ mix background foreground 15% }}",
    "input": "{{ mix background foreground 24% }}",
    "focus": "{{ accent }}",
    "accent": "{{ accent }}",
    "accentForeground": "{{ background }}",
    "secondary": "{{ mix background foreground 6% }}",
    "secondaryForeground": "{{ foreground }}",
    "muted": "{{ mix background foreground 5% }}",
    "mutedForeground": "{{ mix foreground background 30% }}",
    "placeholder": "{{ mix foreground background 34% }}",
    "secondaryLabel": "{{ mix foreground background 30% }}",
    "iconMuted": "{{ mix foreground background 30% }}",
    "error": "{{ red }}",
    "errorForeground": "{{ mix red foreground 35% }}",
    "errorSurface": "{{ mix background red 12% }}",
    "warning": "{{ yellow }}",
    "warningForeground": "{{ mix yellow foreground 35% }}",
    "warningSurface": "{{ mix background yellow 12% }}",
    "update": "{{ accent }}",
    "updateForeground": "{{ mix accent foreground 30% }}",
    "updateSurface": "{{ mix background accent 16% }}",
    "accentSurface": "{{ mix background accent 16% }}",
    "accentSurfaceForeground": "{{ foreground }}",
    "messageSurface": "{{ mix background foreground 9% }}",
    "messageForeground": "{{ foreground }}",
    "messageAction": "{{ accent }}",
    "messageActionForeground": "{{ background }}",
    "messageActionHover": "{{ mix accent foreground 15% }}",
    "codeBackground": "{{ mix background foreground 5% }}",
    "codeForeground": "{{ foreground }}",
    "sidebar": "{{ mix background foreground 9% }}",
    "sidebarForeground": "{{ foreground }}",
    "sidebarMutedForeground": "{{ mix foreground background 30% }}",
    "sidebarControlSurface": "{{ mix background foreground 14% }}",
    "sidebarRowHover": "{{ mix background foreground 13% }}",
    "sidebarRowActive": "{{ mix background accent 14% }}",
    "sidebarRowSelected": "{{ mix background accent 20% }}",
    "sidebarBorder": "{{ mix background foreground 15% }}",
    "terminalBackground": "{{ background }}",
    "terminalForeground": "{{ foreground }}",
    "terminalCursor": "{{ accent }}",
    "terminalSelection": "{{ mix background accent 24% }}",
    "terminalScrollbar": "{{ mix background foreground 18% }}",
    "terminalScrollbarHover": "{{ mix background foreground 28% }}"
  }
}
